### PR TITLE
Added method to convert ARGON output to a .trees file.

### PR DESCRIPTION
**Pull request by gtsambos**
Don't know if tsconvert is getting much love these days, but I've been using recently to convert some ARGON output into tree sequences, so I'm going to add a few little things that have made it workable for me.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM, thanks @gtsambos !

**Comment by gtsambos** [comment]
I'm not going to have time to add tests for this extra method right now, but will make an issue so I remember. (I think this is a pretty niche method in any case).

**Comment by benjeffery** [comment]
Funnily enough I'm working on tsconvert currently - planning a first release, so this has come at a great time!

**Comment by benjeffery** [comment]
I've pushed an updated commit here to make the linting happy.

**Pull request merged**
